plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

def jitProps = gradle.startParameter.projectProperties
version = jitProps['version'] ?: project.mod_version
group = jitProps['group'] ?: project.maven_group

repositories {
    mavenCentral()
    maven { url = "https://maven.fabricmc.net/" }
    maven { url = "https://libraries.minecraft.net/" }
    maven { url = "https://jitpack.io" }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"

    implementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation "net.kyori:adventure-platform-fabric:${project.adventure_platform_version}"
    implementation "net.kyori:adventure-text-serializer-legacy:${project.adventure_version}"

    implementation("com.github.Browsit.ConversationAPI:conversation-api:${project.conversation_version}") {
        changing = true
        exclude group: "net.kyori", module: "adventure-platform-api"
        exclude group: "net.kyori", module: "adventure-api"
    }
    implementation("com.github.Browsit.ConversationAPI:conversation-impl:${project.conversation_version}") {
        changing = true
        exclude group: "net.kyori", module: "adventure-platform-api"
        exclude group: "net.kyori", module: "adventure-api"
        exclude group: "net.kyori", module: "adventure-text-serializer-legacy"
    }

    implementation fileTree(dir: "libs", include: ["*.jar"])
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

def targetJavaVersion = 25
tasks.withType(JavaCompile).configureEach {
    options.release = targetJavaVersion
    options.encoding = "UTF-8"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    withSourcesJar()
}

base {
    archivesName = project.archives_base_name
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}